# Complete documetation of config values:
# https://github.com/YouHaveTrouble/NotJustNameplates/wiki/Configuration
nameplates:
  default:
    refresh-rate: 10
    billboard: "center"
    frames:
      1:
        text: "<placeholder:displayname>"
        offset-y: 0.2

messages:
  config-reloaded: "<aqua>NJN Config reloaded."
  no-permission: "<red>You do not have permission to use this."
