# Complete documetation of config values:
# https://github.com/YouHaveTrouble/NotJustNameplates/wiki/Configuration
nameplates:
  default:
    refresh-rate: 10
    billboard: "vertical"
    frames:
      1:
        text: "%displayname%"

messages:
  config-reloaded: "<aqua>NJN Config reloaded."
  no-permission: "<red>You do not have permission to use this."
