name: NotJustNameplates
version: "${version}"
main: me.youhavetrouble.notjustnameplates.NotJustNameplates
api-version: "1.20"
authors: ["YouHaveTrouble"]
description: Nameplates using display entities
website: https://youhavetrouble.me
dependencies:
  - name: PlaceholderAPI
    required: false
  - name: SuperVanish
    required: false
  - name: PremiumVanish
    required: false
